version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: 'seo-agency-project-key'
      SECRET: 'seo-agency-project-secret'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'admin123'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads

volumes:
  database:
  uploads: 